/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym.managment.view;

import gym.managment.dao.ActividadDAO;
import gym.managment.model.Actividad;
import gym.managment.model.Entrenador;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ActividadFrame extends javax.swing.JFrame {

    private final ActividadDAO actividadDAO = new ActividadDAO();

    /**
     * Creates new form ActividadFrame
     */
    public ActividadFrame() {
        initComponents();
        cargarEntrenadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BannerPanel = new javax.swing.JPanel();
        ActividadesLabel = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();
        ActividadLabel = new javax.swing.JLabel();
        ListarButton = new javax.swing.JButton();
        GuardarButton = new javax.swing.JButton();
        EntrenadorBox = new javax.swing.JComboBox<>();
        TextAct = new javax.swing.JTextField();
        EntrenadorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DescripcionLabel = new javax.swing.JLabel();
        TextDescripcion = new javax.swing.JTextField();
        DuracionLabel = new javax.swing.JLabel();
        TextDuracion = new javax.swing.JTextField();
        CupoLabel = new javax.swing.JLabel();
        TextCupo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(841, 566));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(841, 566));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BannerPanel.setBackground(new java.awt.Color(230, 126, 34));
        BannerPanel.setMinimumSize(new java.awt.Dimension(841, 120));
        BannerPanel.setPreferredSize(new java.awt.Dimension(841, 120));
        BannerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ActividadesLabel.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        ActividadesLabel.setForeground(new java.awt.Color(255, 255, 255));
        ActividadesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActividadesLabel.setText("Actividades");
        ActividadesLabel.setFocusable(false);
        ActividadesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BannerPanel.add(ActividadesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 841, 120));

        MenuButton.setBackground(new java.awt.Color(0, 0, 0));
        MenuButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("Menu");
        MenuButton.setBorderPainted(false);
        MenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuButton.setFocusPainted(false);
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        BannerPanel.add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 90, 35));

        jPanel1.add(BannerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 841, 120));

        ActividadLabel.setBackground(new java.awt.Color(0, 0, 0));
        ActividadLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ActividadLabel.setForeground(new java.awt.Color(255, 255, 255));
        ActividadLabel.setText("Actividad:");
        jPanel1.add(ActividadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 28));

        ListarButton.setBackground(new java.awt.Color(230, 126, 34));
        ListarButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ListarButton.setForeground(new java.awt.Color(255, 255, 255));
        ListarButton.setText("Listar");
        ListarButton.setBorderPainted(false);
        ListarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListarButton.setFocusPainted(false);
        ListarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ListarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 120, 40));

        GuardarButton.setBackground(new java.awt.Color(230, 126, 34));
        GuardarButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GuardarButton.setForeground(new java.awt.Color(255, 255, 255));
        GuardarButton.setText("Guardar");
        GuardarButton.setBorderPainted(false);
        GuardarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GuardarButton.setFocusPainted(false);
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 120, 40));

        EntrenadorBox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EntrenadorBox.setForeground(new java.awt.Color(255, 255, 255));
        EntrenadorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EntrenadorBox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        EntrenadorBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EntrenadorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrenadorBoxActionPerformed(evt);
            }
        });
        jPanel1.add(EntrenadorBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, 28));

        TextAct.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TextAct.setForeground(new java.awt.Color(255, 255, 255));
        TextAct.setText("Actividad");
        TextAct.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        TextAct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextAct.setPreferredSize(new java.awt.Dimension(68, 19));
        TextAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActActionPerformed(evt);
            }
        });
        jPanel1.add(TextAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 180, 28));

        EntrenadorLabel.setBackground(new java.awt.Color(0, 0, 0));
        EntrenadorLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        EntrenadorLabel.setForeground(new java.awt.Color(255, 255, 255));
        EntrenadorLabel.setText("Entrenador/a:");
        jPanel1.add(EntrenadorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 28));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Duracion", "Cupo Max", "Entrenador / a"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(230, 126, 34));
        jTable1.setSelectionBackground(new java.awt.Color(230, 126, 34));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 490, 380));

        DescripcionLabel.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DescripcionLabel.setForeground(new java.awt.Color(255, 255, 255));
        DescripcionLabel.setText("Descripcion:");
        jPanel1.add(DescripcionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 28));

        TextDescripcion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TextDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        TextDescripcion.setText("Agregue descripcion ");
        TextDescripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        TextDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(TextDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 180, 28));

        DuracionLabel.setBackground(new java.awt.Color(0, 0, 0));
        DuracionLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DuracionLabel.setForeground(new java.awt.Color(255, 255, 255));
        DuracionLabel.setText("Duracion(min):");
        jPanel1.add(DuracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, 28));

        TextDuracion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TextDuracion.setForeground(new java.awt.Color(255, 255, 255));
        TextDuracion.setText("                 00:00");
        TextDuracion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        TextDuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDuracionActionPerformed(evt);
            }
        });
        jPanel1.add(TextDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 180, 28));

        CupoLabel.setBackground(new java.awt.Color(0, 0, 0));
        CupoLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CupoLabel.setForeground(new java.awt.Color(255, 255, 255));
        CupoLabel.setText("Cupo Maximo:");
        jPanel1.add(CupoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 28));

        TextCupo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TextCupo.setForeground(new java.awt.Color(255, 255, 255));
        TextCupo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        TextCupo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TextCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 180, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 860, 566));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrenadorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrenadorBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrenadorBoxActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        new MenuFrame().setVisible(true);  // abre el menú principal
        dispose(); // cierra ActividadFrame
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
        try {
            String nombre = TextAct.getText();
            String descripcion = TextDescripcion.getText();
            int duracion = Integer.parseInt(TextDuracion.getText());
            int cupo = Integer.parseInt(TextCupo.getText());
            String nombreEntrenador = EntrenadorBox.getSelectedItem().toString();

            if (nombre.isEmpty() || descripcion.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
                return;
            }
            // Crear objeto Actividad con los datos del form
            Actividad a = new Actividad();
            a.setNombreActividad(nombre);
            a.setDescripcion(descripcion);
            a.setDuracionMinutos(duracion);
            a.setCupoMaximo(cupo);

            // Asignar entrenador (solo nombre por ahora)
            Entrenador e = new Entrenador();
            e.setNombreEntrenador(nombreEntrenador);
            a.setEntrenador(e);

            actividadDAO.insertar(a);
            JOptionPane.showMessageDialog(this, "Actividad guardada correctamente");
            listarActividades();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Duración y cupo deben ser números válidos");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_GuardarButtonActionPerformed

    private void ListarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarButtonActionPerformed
        listarActividades();
    }//GEN-LAST:event_ListarButtonActionPerformed

    private void listarActividades() {
        try {
            List<Actividad> lista = actividadDAO.listar();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (Actividad a : lista) {

                String nombreEntrenador = (a.getEntrenador() != null)
                        ? a.getEntrenador().getNombreEntrenador()
                        : "Sin asignar";

                model.addRow(new Object[]{
                    a.getIdActividad(),
                    a.getNombreActividad(),
                    a.getDescripcion(),
                    a.getDuracionMinutos(),
                    a.getCupoMaximo(),
                    nombreEntrenador
                    
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al listar actividades: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
    private void cargarEntrenadores() {
    try {
        gym.managment.dao.EntrenadorDAO entrenadorDAO = new gym.managment.dao.EntrenadorDAO();
        java.util.List<gym.managment.model.Entrenador> lista = entrenadorDAO.listar();

        // Limpiar el ComboBox
        EntrenadorBox.removeAllItems();

        // Cargar nombres de entrenadores desde la base
        for (gym.managment.model.Entrenador e : lista) {
            EntrenadorBox.addItem(e.getNombreEntrenador());
        }

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar entrenadores: " + ex.getMessage());
        ex.printStackTrace();
    }
}


    private void TextActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActActionPerformed

    private void TextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDescripcionActionPerformed

    private void TextDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDuracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActividadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActividadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActividadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActividadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ActividadFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActividadLabel;
    private javax.swing.JLabel ActividadesLabel;
    private javax.swing.JPanel BannerPanel;
    private javax.swing.JLabel CupoLabel;
    private javax.swing.JLabel DescripcionLabel;
    private javax.swing.JLabel DuracionLabel;
    private javax.swing.JComboBox<String> EntrenadorBox;
    private javax.swing.JLabel EntrenadorLabel;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JButton ListarButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JTextField TextAct;
    private javax.swing.JTextField TextCupo;
    private javax.swing.JTextField TextDescripcion;
    private javax.swing.JTextField TextDuracion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
