/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym.managment.view;

import gym.managment.dao.ClienteDAO;
import gym.managment.model.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tatiana
 */
public class ClienteFrame extends javax.swing.JFrame {

    private final ClienteDAO clienteDAO = new ClienteDAO();

    public ClienteFrame() {
        initComponents();
        ButtonListar.addActionListener(evt -> ButtonListarActionPerformed(evt));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextTel = new javax.swing.JTextField();
        LabelTelefono = new javax.swing.JLabel();
        ButtonListar = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();
        DNITextField = new javax.swing.JTextField();
        NombreTextField = new javax.swing.JTextField();
        LabelDni = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        BannerPanel = new javax.swing.JPanel();
        ClienteLabel = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(841, 566));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(841, 544));
        jPanel1.setPreferredSize(new java.awt.Dimension(841, 566));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelActionPerformed(evt);
            }
        });
        jPanel1.add(TextTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, 30));

        LabelTelefono.setBackground(new java.awt.Color(0, 0, 0));
        LabelTelefono.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        LabelTelefono.setText("Telefono:");
        jPanel1.add(LabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 30));

        ButtonListar.setBackground(new java.awt.Color(230, 126, 34));
        ButtonListar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonListar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonListar.setText("Listar");
        ButtonListar.setBorderPainted(false);
        ButtonListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonListar.setFocusPainted(false);
        ButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, 45));

        ButtonGuardar.setBackground(new java.awt.Color(230, 126, 34));
        ButtonGuardar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonGuardar.setText("Guardar");
        ButtonGuardar.setBorderPainted(false);
        ButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonGuardar.setFocusPainted(false);
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 45));
        jPanel1.add(DNITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 250, 30));
        jPanel1.add(NombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 250, 30));

        LabelDni.setBackground(new java.awt.Color(0, 0, 0));
        LabelDni.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LabelDni.setForeground(new java.awt.Color(255, 255, 255));
        LabelDni.setText("DNI:");
        jPanel1.add(LabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 30));

        NombreLabel.setBackground(new java.awt.Color(0, 0, 0));
        NombreLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        NombreLabel.setText("Nombre:");
        jPanel1.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 30));

        TablaCliente.setBackground(new java.awt.Color(0, 0, 0));
        TablaCliente.setForeground(new java.awt.Color(255, 255, 255));
        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdCliente", "Nombre", "DNI", "Telefono"
            }
        ));
        TablaCliente.setGridColor(new java.awt.Color(230, 126, 34));
        TablaCliente.setRowHeight(25);
        TablaCliente.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TablaCliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 360, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 841, 446));

        BannerPanel.setBackground(new java.awt.Color(230, 126, 34));
        BannerPanel.setPreferredSize(new java.awt.Dimension(841, 120));
        BannerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClienteLabel.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        ClienteLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClienteLabel.setText("CLIENTE");
        BannerPanel.add(ClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 250, 40));

        MenuButton.setBackground(new java.awt.Color(0, 0, 0));
        MenuButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("Menú");
        MenuButton.setBorderPainted(false);
        MenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuButton.setFocusPainted(false);
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        BannerPanel.add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 90, 35));

        getContentPane().add(BannerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 841, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed

        new MenuFrame().setVisible(true);  // abre el menú principal
        dispose(); // cierra ClienteFrame


    }//GEN-LAST:event_MenuButtonActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        try {
            String nombre = NombreTextField.getText();
            String telefono = TextTel.getText();
            String dniTexto = DNITextField.getText();

            if (nombre.isEmpty() || telefono.isEmpty() || dniTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
                return;
            }

            int dni = Integer.parseInt(dniTexto);

            Cliente c = new Cliente();
            c.setNombreCliente(nombre);
            c.setDni(dni);
            c.setTelefono(telefono);

            clienteDAO.insertar(c);
            JOptionPane.showMessageDialog(this, "Cliente guardado correctamente");
            listarClientes();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El DNI debe ser un numero valido");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar" + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void ButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarActionPerformed
        listarClientes();    }//GEN-LAST:event_ButtonListarActionPerformed

    private void listarClientes() {
        try {
            List<Cliente> lista = clienteDAO.listar();
            DefaultTableModel model = (DefaultTableModel) TablaCliente.getModel();
            model.setRowCount(0);

            for (Cliente c : lista) {
                model.addRow(new Object[]{
                    c.getIdCliente(),
                    c.getNombreCliente(),
                    c.getDni(),
                    c.getTelefono()
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar informacion" + ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BannerPanel;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonListar;
    private javax.swing.JLabel ClienteLabel;
    private javax.swing.JTextField DNITextField;
    private javax.swing.JLabel LabelDni;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTextField TextTel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
