/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym.managment.view;

import gym.managment.dao.EntrenadorDAO;
import gym.managment.model.Entrenador;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;



/**
 *
 * @author Tatiana
 */
public class EntrenadorFrame extends javax.swing.JFrame {

    private final EntrenadorDAO entrenadorDAO = new EntrenadorDAO();

    /**
     * Creates new form EntrenadorFrame
     */
    public EntrenadorFrame() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Nombre", "Actividad", "Experiencia"}
        );
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        ListarButton = new javax.swing.JButton();
        GuardarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ActividadLabel = new javax.swing.JLabel();
        ActividadTextField = new javax.swing.JTextField();
        NombreTextField = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        BannerPanel = new javax.swing.JPanel();
        EntrenadoresLabel = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(841, 566));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(841, 566));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListarButton.setBackground(new java.awt.Color(230, 126, 34));
        ListarButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ListarButton.setForeground(new java.awt.Color(255, 255, 255));
        ListarButton.setText("Listar");
        ListarButton.setBorderPainted(false);
        ListarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListarButton.setFocusPainted(false);
        ListarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ListarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, 40));

        GuardarButton.setBackground(new java.awt.Color(230, 126, 34));
        GuardarButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        GuardarButton.setForeground(new java.awt.Color(255, 255, 255));
        GuardarButton.setText("Guardar");
        GuardarButton.setBorderPainted(false);
        GuardarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GuardarButton.setFocusPainted(false);
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, 40));

        jTable1.setBackground(new java.awt.Color(28, 28, 28));
        jTable1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Actividad", "Experiencia"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(230, 126, 34));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(230, 126, 34));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 450, 300));

        ActividadLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ActividadLabel.setForeground(new java.awt.Color(255, 255, 255));
        ActividadLabel.setText("Actividad: ");
        jPanel1.add(ActividadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 30));

        ActividadTextField.setBackground(new java.awt.Color(0, 0, 0));
        ActividadTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ActividadTextField.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ActividadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, 25));

        NombreTextField.setBackground(new java.awt.Color(0, 0, 0));
        NombreTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NombreTextField.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(NombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 150, 25));

        NombreLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        NombreLabel.setText("Nombre:");
        jPanel1.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 841, 446));

        BannerPanel.setBackground(new java.awt.Color(230, 126, 34));
        BannerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EntrenadoresLabel.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        EntrenadoresLabel.setForeground(new java.awt.Color(255, 255, 255));
        EntrenadoresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EntrenadoresLabel.setText("ENTRENADORES");
        EntrenadoresLabel.setPreferredSize(new java.awt.Dimension(841, 120));
        BannerPanel.add(EntrenadoresLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 35, 300, 40));

        MenuButton.setBackground(new java.awt.Color(0, 0, 0));
        MenuButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("Menú");
        MenuButton.setBorderPainted(false);
        MenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        BannerPanel.add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 90, 35));

        getContentPane().add(BannerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 841, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
        try {
            String nombre = NombreTextField.getText();
            String especialidad = ActividadTextField.getText();

            if (nombre.isEmpty() || especialidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
                return;
            }

            Entrenador e = new Entrenador();
            e.setNombreEntrenador(nombre);
            e.setEspecialidad(especialidad);

            entrenadorDAO.insertar(e);
            JOptionPane.showMessageDialog(this, "entrenador guardado correctamente");
            listarEntrenadores();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar" + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_GuardarButtonActionPerformed

    private void ListarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarButtonActionPerformed
        listarEntrenadores();
    }//GEN-LAST:event_ListarButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        new MenuFrame().setVisible(true);  // abre el menú
        dispose(); // cierra EntrenadorFrame    }//GEN-LAST:event_MenuButtonActionPerformed
    }
    private void listarEntrenadores() {
    try {
        List<Entrenador> lista = entrenadorDAO.listar();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Entrenador e : lista) {
            model.addRow(new Object[]{
                e.getIdEntrenador(),
                e.getNombreEntrenador(),
                e.getEspecialidad()
            });
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "❌ Error al listar: " + ex.getMessage());
        ex.printStackTrace();
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntrenadorFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EntrenadorFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActividadLabel;
    private javax.swing.JTextField ActividadTextField;
    private javax.swing.JPanel BannerPanel;
    private javax.swing.JLabel EntrenadoresLabel;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JButton ListarButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
