/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package gym.managment.view;

import java.awt.Toolkit;

/**
 *
 * @author Tatiana
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenúFrame
     */
    public MenuFrame() {
        initComponents();
        // establece el ícono del programa
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/gym/managment/view/resources/IconoGym.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonClientes = new javax.swing.JButton();
        ButtonAct = new javax.swing.JButton();
        ButtonEntrenadores = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GYM CHECK - Control de Gimnasio");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(841, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(841, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonClientes.setBackground(new java.awt.Color(230, 126, 34));
        ButtonClientes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonClientes.setText("Clientes");
        ButtonClientes.setBorderPainted(false);
        ButtonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClientes.setFocusPainted(false);
        ButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientesActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 140, 40));

        ButtonAct.setBackground(new java.awt.Color(230, 126, 34));
        ButtonAct.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonAct.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAct.setText("Actividades");
        ButtonAct.setBorderPainted(false);
        ButtonAct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAct.setFocusPainted(false);
        ButtonAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 140, 40));

        ButtonEntrenadores.setBackground(new java.awt.Color(230, 126, 34));
        ButtonEntrenadores.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonEntrenadores.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEntrenadores.setText("Entrenadores");
        ButtonEntrenadores.setBorderPainted(false);
        ButtonEntrenadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEntrenadores.setFocusPainted(false);
        ButtonEntrenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEntrenadoresActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEntrenadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 140, 40));

        ButtonSalir.setBackground(new java.awt.Color(230, 126, 34));
        ButtonSalir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSalir.setText("Salir");
        ButtonSalir.setBorderPainted(false);
        ButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonSalir.setFocusPainted(false);
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 140, 40));

        jPanel2.setBackground(new java.awt.Color(230, 126, 34));
        jPanel2.setMinimumSize(new java.awt.Dimension(841, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/managment/view/resources/IconoGym.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(841, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(841, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(841, 120));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEntrenadoresActionPerformed
        new EntrenadorFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonEntrenadoresActionPerformed

    private void ButtonActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActActionPerformed
        new ActividadFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonActActionPerformed

    private void ButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientesActionPerformed
        new ClienteFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAct;
    private javax.swing.JButton ButtonClientes;
    private javax.swing.JButton ButtonEntrenadores;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
